### ISSUE TITLE
Settings area at user profile

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#109]
A settings area dedicated for the extension with a specified icon next to it would be great for offering users customization options.

- [ ] Font Awesome & Material Icons
- [ ] Material Design 2014 (Cards & elevation focused) & Material Design 2018 (Borders & colors focused)
- [ ] Material Icons: Filled, Outlined, Rounded, Two-tone, Sharp.

Feel free to suggest more options to this list.

## Roadmap
- [x] Complete preparations for Material Icon options.
- [ ] Create settings page with a representative icon and title.
- [x] Create en.yml translations file.
- [x] Translate to Turkish.
- [x] Translate to Italian.
- [x] Create 2018.less style file.
- [ ] Complete settings page design.

**Comment by ardacebi** [comment]
Guide for icon styles:

> 
>  
>  Hey folks, the font is actually available. Looks like the spec hasn't been finalized yet? We need to wait for them to finalize, test, publish, etc.
>  
>  I am not sure what the spec is going to look like but for those who want to have a non-spec implementation, you could do the following to match what the material icons website does:
>  
>  Import the following 6 style sheets made available on the material icons page:
>  
>      https://storage.googleapis.com/non-spec-apps/mio-icons/latest/styles.css
>      https://storage.googleapis.com/non-spec-apps/mio-icons/latest/baseline.css
>      https://storage.googleapis.com/non-spec-apps/mio-icons/latest/sharp.css
>      https://storage.googleapis.com/non-spec-apps/mio-icons/latest/outline.css
>      https://storage.googleapis.com/non-spec-apps/mio-icons/latest/round.css
>     https://storage.googleapis.com/non-spec-apps/mio-icons/latest/twotone.css
> 
>  Then use the same markup as the website (seems to be similar to font awesome?)
> 
> ```
> <i class="baseline-router icon-image-preview"></i>
> <i class="outline-router icon-image-preview"></i>
> <i class="round-router icon-image-preview"></i>
> <i class="twotone-router icon-image-preview"></i>
> <i class="sharp-router icon-image-preview"></i>
> ```
> 
> > Here is a sample HTML file that demonstrates what is needed.
> 
> ```
> <!DOCTYPE html>
> <html>
> 
> <head>
>     <meta charset="utf-8">
>     <title>Material Icons</title>
>     <meta name="viewport" content="width=device-width, initial-scale=1">
>     <link rel="stylesheet" href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css">
>     <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Mono">
>     <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500">
>     <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
>     <link rel="stylesheet" href="https://storage.googleapis.com/non-spec-apps/mio-icons/latest/styles.css">
>     <link rel="stylesheet" href="https://storage.googleapis.com/non-spec-apps/mio-icons/latest/baseline.css">
>     <link rel="stylesheet" href="https://storage.googleapis.com/non-spec-apps/mio-icons/latest/sharp.css">
>     <link rel="stylesheet" href="https://storage.googleapis.com/non-spec-apps/mio-icons/latest/outline.css">
>     <link rel="stylesheet" href="https://storage.googleapis.com/non-spec-apps/mio-icons/latest/round.css">
>     <link rel="stylesheet" href="https://storage.googleapis.com/non-spec-apps/mio-icons/latest/twotone.css">
>     <style>
>         .pad {
>             padding: 10px;
>         }
> 
>         .round-corners {
>             border-radius: 8px;
>         }
> 
>         .my-0 {
>             margin-top: 0px;
>             margin-bottom: 0px;
>         }
> 
>         .underline {
>             width: 100px;
>             height: 2px;
>             border-radius: 1px;
>             background-color: currentColor;
>             margin-top: 12px;
>         }
>     </style>
> </head>
> 
> <body class="mdc-typography">
>     <header class="mdc-toolbar mdc-toolbar--fixed demo-toolbar">
>         <div class="mdc-toolbar__row">
>             <section class="mdc-toolbar__section mdc-toolbar__section--align-start">
>                 <span class="mdc-toolbar__title">Material Icons</span>
>             </section>
>         </div>
>     </header>
>     <main>
>         <div class="mdc-toolbar-fixed-adjust">
>             <div class="demo-grid mdc-layout-grid">
>                 <div class="mdc-layout-grid__inner">
>                     <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12 mdc-layout-grid__cell--span-8-tablet mdc-layout-grid__cell--span-4-phone mdc-elevation--z2 pad round-corners">
>                         <div class="mdc-list-group">
>                             <h3 class="mdc-list-group__subheader">Imports</h3>
>                             <div class="mdc-list-group__subheader underline"></div>
>                             <ul class="mdc-list">
>                                 <li class="mdc-list-item">Import the following 6 stylesheets made available by google:</li>
>                                 <li class="mdc-list-item">https://storage.googleapis.com/non-spec-apps/mio-icons/latest/styles.css</li>
>                                 <li class="mdc-list-item">https://storage.googleapis.com/non-spec-apps/mio-icons/latest/baseline.css</li>
>                                 <li class="mdc-list-item">https://storage.googleapis.com/non-spec-apps/mio-icons/latest/outline.css</li>
>                                 <li class="mdc-list-item">https://storage.googleapis.com/non-spec-apps/mio-icons/latest/round.css</li>
>                                 <li class="mdc-list-item">https://storage.googleapis.com/non-spec-apps/mio-icons/latest/twotone.css</li>
>                                 <li class="mdc-list-item">https://storage.googleapis.com/non-spec-apps/mio-icons/latest/sharp.css</li>
>                             </ul>
>                             <h3 class="mdc-list-group__subheader">Filled/Baseline</h3>
>                             <div class="mdc-list-group__subheader underline"></div>
>                             <ul class="mdc-list demo-list">
>                                 <li class="mdc-list-item">&lt;i class=&quot;baseline-router icon-image-preview&quot;&gt;&lt;/i&gt;</li>
>                                 <li class="mdc-list-item"><i class="baseline-router icon-image-preview"></i></li>
>                             </ul>
>                             <h3 class="mdc-list-group__subheader">Outline</h3>
>                             <div class="mdc-list-group__subheader underline"></div>
>                             <ul class="mdc-list demo-list">
>                                 <li class="mdc-list-item">&lt;i class=&quot;outline-router icon-image-preview&quot;&gt;&lt;/i&gt;</li>
>                                 <li class="mdc-list-item"><i class="outline-router icon-image-preview"></i></li>
>                             </ul>
>                             <h3 class="mdc-list-group__subheader">Round</h3>
>                             <div class="mdc-list-group__subheader underline"></div>
>                             <ul class="mdc-list demo-list">
>                                 <li class="mdc-list-item">&lt;i class=&quot;round-router icon-image-preview&quot;&gt;&lt;/i&gt;</li>
>                                 <li class="mdc-list-item"><i class="round-router icon-image-preview"></i></li>
>                             </ul>
>                             <h3 class="mdc-list-group__subheader">Two-Tone</h3>
>                             <div class="mdc-list-group__subheader underline"></div>
>                             <ul class="mdc-list demo-list">
>                                 <li class="mdc-list-item">&lt;i class=&quot;twotone-router icon-image-preview&quot;&gt;&lt;/i&gt;</li>
>                                 <li class="mdc-list-item"><i class="twotone-router icon-image-preview"></i></li>
>                             </ul>
>                             <h3 class="mdc-list-group__subheader">Sharp</h3>
>                             <div class="mdc-list-group__subheader underline"></div>
>                             <ul class="mdc-list demo-list">
>                                 <li class="mdc-list-item">&lt;i class=&quot;sharp-router icon-image-preview&quot;&gt;&lt;/i&gt;</li>
>                                 <li class="mdc-list-item"><i class="sharp-router icon-image-preview"></i></li>
>                             </ul>
>                         </div>
>                     </div>
>                 </div>
>             </div>
> 
>         </div>
>     </main>
> </body>
> 
> </html>
> ```
>

**Comment by ardacebi** [comment]
I started working on this at the `settings-page` branch but I need help a little.

**Comment by hammerhai** [comment]
This issue will be closed as this was a roadmap for 0.1.0-beta.7 or 0.1.0-beta.8.

It will be recreated for 0.1.0-beta.12 and 0.1.0-beta.13 (yes, we'll be jumping on the bandwagon very quickly this time).
