### ISSUE TITLE
Roadmap for 0.1.0-beta.12+

### ISSUE THREAD

**Issue by KodedScorpius** [Extum/material#156]
The content in this issue will outline the standards that will follow for the roadmap. **These are only likely things which will be implemented and must not be thought of as "reflecting upon final release."**

- [ ] Extension page: Through discussion, we've come to the conclusion that Extum Material will no longer lack customization!

- [ ] Full compatibility with Flarum: No matter what happens with Flarum, we'd like to be able to make it easy for Flarumites to have the ability to upgrade their favorite theme all-year-round! We're hoping to improve support so that we have the ability to upgrade Extum Material before you even have the next version of Flarum installed (if you're not Beta testing).

- [ ] Material Design Icons: No more Font Awesome, unless you like it. All icons except ones where exceptions must be made, will be Material Design. How exciting!

- [ ] MDC components, the unofficial ones: Unfortunately I've tried adding official MDC and it's not working. Through this release, there will be LESS utilized instead, to mimic what an MD component would look and behave like.

### Extension Page
The extension page will have many options like 🔌 Adaptive Mode, 🌑 Night Mode, 🧙‍♂️ Setup Wizard, 🎨 Styles. See below for the operations of the options.

#### Adaptive Mode
Adaptive Mode is the next move towards a new system-wide night mode. It will adhere to the devices preference, instead of forcing a mode that the forum administrator would want.

#### Classic Bundle
While you might like the new Material, you can go back to the old... And guess what, it's even compatible with 0.1.0-beta.12!

#### Night Mode
This is where the forum administrator (you) come in! Lets say you don't like your system-wide night mode on your phone. Well, this option is where you can force everyone to adhere to the policy of your own, they can only have night mode and nothing else.

#### Setup Wizard
Don't get hyped, it's just a setup wizard for Extum Material 🙂

#### Styles
There will be two styles you can choose from, Filled or Outlined. It'd recommended you keep the `default: Outlined` only because it's pErTy.
