### ISSUE TITLE
Roadmap for 0.1.0-beta.12+

### ISSUE THREAD

**Issue by hammerhai** [Extum/material#157]
The content in this issue will outline the standards that will follow for the roadmap. **These are only likely things which will be implemented and must not be thought of as "reflecting upon final release."**

- [ ] Extension page: Through discussion, we've come to the conclusion that Extum Material will no longer lack customization!

- [ ] Full compatibility with Flarum: No matter what happens with Flarum, we'd like to be able to make it easy for Flarumites to have the ability to upgrade their favorite theme all-year-round! We're hoping to improve support so that we have the ability to upgrade Extum Material before you even have the next version of Flarum installed (if you're not Beta testing).

- [ ] Material Design Icons: No more Font Awesome, unless you like it. All icons except ones where exceptions must be made, will be Material Design. How exciting! 

- [ ] MDC components, the unofficial ones: Unfortunately I've tried adding official MDC and it's not working. Through this release, there will be LESS utilized instead, to mimic what an MD component would look and behave like. **I'm taking a look into rendering Flarum using Material-Ui.**

### Extension Page
The extension page will have many options like 🔌 Adaptive Mode, 🗝 Classic Bundle, 🌑 Night Mode, 🧙‍♂️ Setup Wizard, 🎨 Styles. See below for the operations of the options.

#### Adaptive Mode
Adaptive Mode is the next move towards a new system-wide night mode. It will adhere to the devices preference, instead of forcing a mode that the forum administrator would want.

#### Classic Bundle
While you might like the new Material, you can go back to the old... And guess what, it's even compatible with 0.1.0-beta.12!

#### Night Mode
This is where the forum administrator (you) come in! Lets say you don't like your system-wide night mode on your phone. Well, this option is where you can force everyone to adhere to the policy of your own, they can only have night mode and nothing else.

#### Setup Wizard
Don't get hyped, it's just a setup wizard for Extum Material 🙂

#### Styles
There will be two styles you can choose from, Filled or Outlined. It'd recommended you keep the `default: Outlined` only because it's pErTy.

### Full compatibility
As we know, Flarum is changing by the second. Here at Extum, we think it's important that we support Extum Material for as long as it can be! From now on, we will be paying close attention to the releases of Flarum to support future releases of Flarum, that you don't even have installed yet.

### Material Design Icons
This year, we've clapped back at Google. We're no longer using [material.io/icons](material.io/icons), but instead [materialdesignicons.com](materialdesignicons.com). Yes there are icons made by Google, but there's more made by the community than by that one Google Designer!

### MDC components, the unofficial ones
Material Design Components for the Web seem like a difficult thing to add to Flarum... so instead we've come up with a solution, code some LESS to make a component replicate that it's one of the Material Library.

**I'm taking a look into rendering Flarum using Material-Ui.**

### Expected release
As of now, 20 April 2020, there is no estimated date. I expect it to be out before 0.1.0-beta.14, but I also would like to wait to make it compatible right away instead of having to push an upgrade a day after Beta 14 has come out. I'd say this was non-discussed, because it is.
